name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/debug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.19.4
      - name: Install dependencies
        run: yarn install
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleDebug
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          # note that you can supply the project id any way you like, it is not secret
          project-id: com.browncat2123.reportmaps
          app-file: app/build/outputs/apk/debug/app-debug.apk
