name: Build and run Maestro tests (React Native Android)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Test Maestro API Key
        run: |
          echo "MAESTRO_API_KEY=$MAESTRO_API_KEY"
      # 1. Checkout source code
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # # 2. Setup Node.js (sesuai request kamu)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20.19.4
      #     cache: yarn

      # # 3. Install JS dependencies
      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      # # 4. Setup Java (Android build)
      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: 17
      #     distribution: temurin

      # # 5. Setup Android SDK
      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3

      # # 6. Build Debug APK (React Native)
      # - name: Build Android Debug APK
      #   working-directory: android
      #   run: ./gradlew assembleDebug

      # # 7. Run Maestro Cloud tests
      # - name: Run Maestro Cloud
      #   uses: mobile-dev-inc/action-maestro-cloud@v1
      #   with:
      #     api-key: ${{ secrets.MAESTRO_API_KEY }}
      #     project-id: com.browncat2123.reportmaps
      #     app-file: android/app/build/outputs/apk/debug/app-debug.apk
